Sprint 1
ShvetsovYura/middle.messenger.praktikum.yandex pull request #4
Opened 2021-07-08 08:15 UTC by ShvetsovYura

2021-07-08 11:35 UTC, nickchamel requested changes
Привет! Хорошая работа, но есть несколько замечаний, ознакомься пожалуйста с комментариями. Плюс у тебя не проходит 1 тест, а так же не работает страницы с изменениями данных профиля, аватара и пароля. и html-файлы было бы неплохо вынести в папку public

2021-07-08 11:35 UTC, nickchamel commented on README.md
> +### Приложение WelcoChat - это мессенджер - "убийца" Telegram
ахах 👍🏼

2021-07-08 11:35 UTC, nickchamel commented on package.json
> +    "dev": "parcel build ./src/index.html --port 3000",
для дев разработки не нужно билд делать, там нужно чтобы работал watcher, который следит за изменениями в файлах, поэтому тут либо просто `parcel ./src/index.html` либо `parcel serve ./src/index.html`.

2021-07-08 11:35 UTC, nickchamel commented on server.js
> +app.use(express.static('dist'));
дубль

2021-07-08 11:35 UTC, nickchamel commented on server.js
> +app.listen(3000, function () {
порт лучше выносить в константу, чтобы была возможность менять его с помощью переменных окружения
`const PORT = process.env.port || 3000`

2021-07-08 11:35 UTC, nickchamel commented on src/404.html
> +    </main>
по заданию вся верстка должна быть реализована в шаблонах, а html-файлы должны сожержать только контейнер, в который из JS-кода будет рендериться шаблон

2021-07-08 11:35 UTC, nickchamel commented on src/500.html
> +    </main>
тут и дальше то же самое

2021-07-08 11:35 UTC, nickchamel commented on src/change-password.html
> +    <script src="./modules/change-password/change-password-page.js"></script>
ты не должен таким образом подключать handlebars. Конечно оно так работает, но это противоречит модульной структуре, ты используешь что-то из глобального скоупа, а в модулях у тебя нет импортов handlebars, что как минимум вводит в заблуждение. Плюс ты связываешь слои приложения. Модуль получается не самостоятельным и зависит от того, что находится в html
Ты здесь подключаешь javascript-файл модуля (в данном случае change-password-page.js). А в этом js ты уже импортируешь handlebars, рендеришь шаблон модуля и вставляешь его в container

2021-07-08 11:35 UTC, nickchamel commented on src/chat.html
> +	<script src="https://cdn.jsdelivr.net/npm/handlebars@latest/dist/handlebars.runtime.js"></script>
здесь и дальше так же

2021-07-08 11:35 UTC, nickchamel commented on src/index.html
> +    </ul>
тут можешь оставить и так)

2021-07-08 11:35 UTC, nickchamel commented on src/modules/change-password/change-password-page.js
> +document.querySelector(".form-container").innerHTML = template();
здесь и дальше тоже самое:
нужно убрать все precompiled файлы. им не место в src проекта.
Взгляни на эту библиотеку https://github.com/belicekm/parcel-plugin-handlebars-precompile
Ты можешь сделать с помощью нее, а можешь импортировать из шаблонов ES6-строки и с помощью handlebars компилить их. Оба варианта хороши.
Если будешь использовать либу, то регистрируй шаблоны в папках самих модулей. То есть здесь импортишь `change-password-page.handlebars` и тут же его регистрируешь, а если его надо будет где-то переиспользовать то ты будешь импортить сам модуль, поэтому шаблон всегда будет зарегистрирован

2021-07-08 11:35 UTC, nickchamel commented on src/modules/profile/profile-page.js
> +document.querySelector(".form-container").innerHTML = Handlebars.templates["profile-page"](data.userinfo);
Здесь и в остальных похожих местах - для лучше читаемости и поддержки лучше не писать все в одну строку а разбить на несколько.
Плюс не забывай про camelCase, как стандарт javascripta `userInfo`
```
const wrapper = document.querySelector(".form-container");
const compileTemplate = Handlebars.templates["profile-page"];
wrapper.innerHTML = compileTemplate(data.userInfo)
```

2021-07-08 15:16 UTC, ShvetsovYura commented on src/change-password.html
> +    <script src="./modules/change-password/change-password-page.js"></script>
При импорте handlebars в модуле (import Handlebars from 'handlebars' возникает ошибка 'Uncaught TypeError: Cannot read property 'extensions' of undefined' (даже, если в модуле больше нет кода - без разницы). Пол дня копаюсь - не могу разобраться.

2021-07-08 15:27 UTC, nickchamel commented on src/change-password.html
> +    <script src="./modules/change-password/change-password-page.js"></script>
![image](https://user-images.githubusercontent.com/28347933/124948936-f5196180-e032-11eb-9f57-e70cc9269609.png)
![image](https://user-images.githubusercontent.com/28347933/124948978-ff3b6000-e032-11eb-8f7e-d7741270fe15.png)
Я просто склонил твой реп и поднял дев 
![image](https://user-images.githubusercontent.com/28347933/124949274-3b6ec080-e033-11eb-8fb1-e2edf31e5033.png)
Выше писал про это

2021-07-09 11:09 UTC, nickchamel requested changes
Отлично! Уже значительно лучше, только ты зря убрал элемент-обертку для приложения (описал подробнее в комменте) и заодно нужно еще чуть стиль кода поправить

2021-07-09 11:09 UTC, nickchamel commented on public/404.html
> +  </body>
ты должен использовать элемент-обертку, а не вставлять в document.body, либо как минимум нужно тогда append элемента делать, а не innerHtml. Потому что сейчас после вставки у тебя пропадает скрипт. А в нем твое приложение, в дальнейшем роутинг, обработчики и прочее

2021-07-09 11:09 UTC, nickchamel commented on public/chat.html
> +</html>
приведи отступы к единому стилю, пожалуйста

2021-07-09 11:09 UTC, nickchamel commented on src/modules/change-password/change-password-page.tpl.js
> +      <input
темплейты тоже к единому стилю, они у тебя друг от друга отличаются

2021-07-09 12:57 UTC, nickchamel approved these changes
Отлично. Успехов в дальнейшем!

2021-07-09 13:07 UTC, merged